/* eslint-disable @next/next/no-img-element */
import Head from "next/head"
import Layout from "../layout"
import { useLanguage } from "@/provider/language"

export default function Home() {
  const { language } = useLanguage()
  return (
    <>
      <Head>
        <title>Xepelin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout pageName="/">
      </Layout>
    </>
  )
}
